export enum Colors {
  OverlayColor = 'var(--overlay-color)',
  RedLight = 'var(--red-light)',
  RedDark = 'var(--red-dark)',
  ColorPrimary = 'var(--color-primary)',
  ColorSecondary = 'var(--color-secondary)',
  Gradient1 = 'var(--gradient-1)',
  Gradient2 = 'var(--gradient-2)',
  Gradient3 = 'var(--gradient-3)',
  Gradient4 = 'var(--gradient-4)',
  Gradient5 = 'var(--gradient-5)',
  Gradient6 = 'var(--gradient-6)',
  Gradient7 = 'var(--gradient-7)',
  Gradient8 = 'var(--gradient-8)',
  Gradient9 = 'var(--gradient-9)',
  Gradient10 = 'var(--gradient-10)',
  ColorBg = 'var(--color-bg)',
  ColorSpecial = 'var(--color-special)',
}
